nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.1.cjs

npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com"
    npmAuthToken: "D9C72893-EBA2-46C8-978F-F0B55A7C277F"

